### PR TITLE
#6 list contacts UI

### PR DESCRIPTION
**Pull request by udai1931**

### CODE REVIEW

**Comment by yedhink** [comment]
@udai1931 I am not sure why in every PR there are like 67 files changes. That's just the wrong way to make a PR

**Comment by yedhink** [comment]
PRs ought to be atomic in nature and fixing a single issue. If you are cramming everything in one PR then it destroys the purpose of a PR itself.

@udai1931 
Moving forward please don't make PRs like this. PR's should fix only the issue and should only consist of files fixing that particular issue. If you need to make an unrelated change, raise another atomic issue and make another PR rather than mixing things up.

**Comment by yedhink** [comment]
@udai1931 Also stop using `Fixes` comment as commit messages. Rather when you raise a PR as the first comment add a `Fixes #xxx, #yyy` comment where `xxx,yyy` etc are issue numbers. So when PR gets merged, the corresponding issues get auto-closed by Github.

**Comment by udai1931** [comment]
@yedhink I found the mistake I was doing which lead this series of commits in each PR. Also, I will keep in mind to use this fixes msg in comments only. 👍🏻

**Pull request merged**
